//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWORKODB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public int BrokerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BrokageCompany { get; set; }
    }
}
